sudo: false
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - clang++-5.0
      - libfuzzer-5.0-dev
env:
  - CC=clang-5.0
  - CFLAGS="-fsanitize=address -fsanitize=coverage=trace-pc-guard,trace-cmp -g"
  - CXX=clang++-5.0
  - CXXFLAGS="-fsanitize=address -fsanitize=coverage=trace-pc-guard,trace-cmp -g"
  - LIBFUZZER=/usr/lib/llvm-5.0/lib/libFuzzer.a
script:
  - cd openssl && CC="$CC $CFLAGS" ./config && make clean && make && cd ..
  - $CXX $CXXFLAGS target.cc  openssl/libssl.a openssl/libcrypto.a $LIBFUZZER -I openssl/include -o handshake_fuzzer